name: CI

on:
    push:
        branches:
            - "**"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20.9.0"

            - name: Install dependencies
              run: yarn install

            - name: Run lint
              run: yarn run lint

            - name: Build
              run: yarn run build
              env:
                  XATA_API_KEY: ${{ secrets.XATA_API_KEY }}
                  XATA_BRANCH: ${{ secrets.XATA_BRANCH }}
                  PRIVATE_GITHUB_THANKS_TOKEN: ${{ secrets.PRIVATE_GITHUB_THANKS_TOKEN }}
