name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.14.0' # You can specify your Node version here

    - name: Install dependencies
      run: yarn install

    - name: Run lint
      run: yarn run lint

    - name: Build
      run: yarn build
